apiVersion: v1
kind: ConfigMap
metadata:
  name: workhub-config
  namespace: workhub
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/workhub"
  SPRING_DATASOURCE_USERNAME: "workhub_user"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
