apiVersion: v1
kind: Service
metadata:
  name: workhub-service
  namespace: workhub
spec:
  selector:
    app: workhub-app
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8080 # Your app's port
  type: LoadBalancer # Use NodePort if testing with minikube
